"""empty message

Revision ID: 0a0a6960f1fd
Revises: 95f4ff80ae32
Create Date: 2020-05-01 20:58:35.071281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0a6960f1fd'
down_revision = '95f4ff80ae32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('time', sa.String(), nullable=False))
    op.drop_column('Show', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'time')
    # ### end Alembic commands ###
